In [2]:
# 챗봇 프로젝트
import pandas as pd

In [14]:
df = pd.read_csv('소상공인시장진흥공단_전국 온누리상품권 가맹점 현황_20250731.csv')
df.head()

,가맹점명,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
0,초마맨1981,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y,2025
1,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y,2025
2,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y,2025
3,참새 방앗간,권율 골목형상점가,경기,육전 새우전,Y,Y,2025
4,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y,2025

In [15]:
df2 = pd.read_csv('소상공인시장진흥공단_온누리상품권 지역별 판매현황_20241231.csv')
df2.head()

,구분,2015년_판매금액(억원),2016년_판매금액(억원),2017년_판매금액(억원),2018년_판매금액(억원),2019년_판매금액(억원),2020년_판매금액(억원),2021년_판매금액(억원),2022년_판매금액(억원),2023년_판매금액(억원),2024년_판매금액(억원)
0,서울,1968.9,2500.6,2064.6,2884.2,3327.9,7183.3,5058.3,3903.4,4536.2,5201.1
1,부산,1022.8,1260.6,1658.8,2117.5,2592.8,5910.1,4506.9,3928.8,3763.3,5262.0
2,대구,678.5,897.9,1166.4,1578.5,1842.8,5684.2,3606.4,2868.3,2856.8,3584.0
3,인천,286.0,439.1,438.7,634.9,639.7,1582.1,1164.6,750.8,721.1,921.3
4,광주,267.1,375.3,467.2,681.3,716.9,1368.5,904.3,728.0,677.4,1146.6

In [16]:
df3 = pd.read_csv('소상공인시장진흥공단_온누리상품권 지역별 회수현황_20241231.csv')
df3.head()

,구분,2015년_회수금액(억원),2016년_회수금액(억원),2017년_회수금액(억원),2018년_회수금액(억원),2019년_회수금액(억원),2020년_회수금액(억원),2021년_회수금액(억원),2022년_회수금액(억원),2023년_회수금액(억원),2024년_회수금액(억원)
0,서울,1460.6,2131.7,2257.8,2889.8,3449.0,6806.3,7281.2,6194.1,7288.1,9361.5
1,부산,1147.0,1647.9,1916.3,2454.1,2909.2,5808.0,5606.2,4010.3,5038.3,5475.8
2,대구,844.8,1246.4,1520.2,2013.8,2332.8,6066.5,5812.6,4460.2,5536.2,8124.6
3,인천,344.7,498.6,491.3,606.9,632.8,1352.6,1143.0,752.4,896.8,1107.9
4,광주,309.7,444.5,569.6,800.3,857.0,1331.2,1282.3,835.1,963.1,1308.1